### PR TITLE
Added setup video link in readme

### LINKED ISSUE #70: Add the setup tutorial video to Readme.md
### Is your feature request related to a problem? Please describe.
Newcomers find it difficult to setup the project locally on their system due to vague instructions.

### Describe the solution you'd like
Add a setup tutorial video to Readme.md. 
The [video](https://youtu.be/_b2RQGbYN9w) is already been recorded by @codesankalp.

### PR DESCRIPTION
**Pull request by Rahulm2310**
### Description

Added setup video link in readme.md

Fixes #70 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

image

### Checklist:

- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Rahulm2310** [comment]
@isabelcosta Can you please review this PR ?

**Review by codesankalp — APPROVED** [review]
LGTM @Rahulm2310 :+1: .

**Review by Amulya-coder — APPROVED** [review]
LGTM!! @Rahulm2310 🎉.

**Review by isabelcosta — APPROVED** [review]
Thank you for your contribution @Rahulm2310 👏

**Pull request merged**
