### PR TITLE
Feature/added roadmap link

### LINKED ISSUE #181: Add roadmap link to the documentation section in readme
## Is your feature request related to a problem? Please describe

We can get the idea of the features and project status by  the project roadmap, hence a link to the same should be present in the readme.

## Describe the solution you'd like

Add the roadmap link under documentation section in Readme.

### PR DESCRIPTION
**Pull request by Samridhi-98**
### Description

Fixes #181 

### Type of Change:

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Samridhi-98** [comment]
@Aaishpra @isabelcosta please review my PR.

**Comment by Samridhi-98** [comment]
@codesankalp  @Aaishpra  @keshakaneria  please review my PR.

**Review by isabelcosta — CHANGES_REQUESTED** [review]
@Samridhi-98 thank you for contributing 🙌🏾 

This looks good, could you just undo the changes to `yarn.lock` file. Since this seem to be unrelated to the ticket. If you remove those, then we can merge without testing, since it does not affect production code.

**Comment by Samridhi-98** [comment]
@isabelcosta  Done, please review :)

**Review by isabelcosta — CHANGES_REQUESTED** [review]
I see the file is still there. @keshakaneria @codesankalp Could you help here 🤔 
@Samridhi-98 the idea is to not have `yarn.lock` showing up in the changes tab. Could you look into how, to dismiss the changes in the file?

**Pull request closed without merging**
