### PR TITLE
.github: deleted ISSUE_TEMPLATE and changed bug_report.md link (#96)

### LINKED ISSUE #96: Docs: Delete ISSUE TEMPLATE folder from .github
## Description

As an org admin or maintainer,
We need to maintain 1 version of issue templates used in the organization,
so that we can avoid duplicating work and having different versions of the templates when we want to use the same ones across all projects.

Because the issue templates are now on https://github.com/anitab-org/.github, we don't need to have issue templates present in the repository. Read more about these type of files here https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

### Update [Required]

    

- [ ] Delete .github/ISSUE_TEMPLATE
- [ ] Update the [new link](https://github.com/anitab-org/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) for bug_report.md in Contributing.md

## Definition of Done

All of the required items are completed.

- [ ]  Approval by 1 mentor.

### Estimation

0.5 hours

### PR DESCRIPTION
**Pull request by tosimia**
### Description
-  Deleted ISSUE TEMPLATE folder from .github
-  Changed bug_report.md link

Fixes #96  

### Type of Change:

- Documentation

### Checklist:

- [x] My PR follows the style guidelines of this project

### CODE REVIEW

**Review by isabelcosta — APPROVED** [review]
Amazing work @tosimiadesoye 👏🏾 
Thank you for your contribution!

**Review by codesankalp — APPROVED** [review]

**Review by Amulya-coder — APPROVED** [review]

**Comment by haelmj** [comment]
Good work @tosimiadesoye

**Review by haelmj — APPROVED** [review]

**Comment by tosimia** [comment]
> Amazing work @tosimiadesoye 👏🏾
> Thank you for your contribution!

Thank you @isabelcosta :smiley:

**Comment by tosimia** [comment]
> Good work @tosimiadesoye

Thanks @haelmj  :smiley:

**Pull request merged**
