### PR TITLE
Update dependencies in the project

### LINKED ISSUE #177: Updating all the dependencies in the project
## Task

- Updating all the project dependencies to their latest version.

### PR DESCRIPTION
**Pull request by umair-fayaz**
### Description

Fixes #177 Updating all the dependencies in the project

### Type of Change:

- Code

**Code/Quality Assurance Only**

- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Tested locally by doing "npm install" and then using the app in browser

### Checklist:

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Aaishpra** [comment]
Please write the issues number and a small PR description.

**Review by Aaishpra — DISMISSED** [review]

**Comment by umair-fayaz** [comment]
Issue #177.
Updated package.json using npm-check-updates

**Review by codesankalp — CHANGES_REQUESTED** [review]
@umair-fayaz When I tried to test it locally, it gave me this error:
image

I think you just updated the dependencies but the main issue was to update dependency making sure compatibility of other dependencies.

**Comment by umair-fayaz** [comment]
> @umair-fayaz When I tried to test it locally, it gave me this error: image
> 
> I think you just updated the dependencies but the main issue was to update dependency making sure compatibility of other dependencies.

May I know how you got this error. I tried it locally and it worked fine for me

**Comment by codesankalp** [comment]
> May I know how you got this error. I tried it locally and it worked fine for me

I clone your repo and run command `npm install`

**Comment by umair-fayaz** [comment]
> > May I know how you got this error. I tried it locally and it worked fine for me
> 
> I clone your repo and run command `npm install`

I tried the same once again. Install is happening and the app loads in browser. I am getting 104 vulnerabilities (85 moderate, 18 high, 1 critical) after npm install but the same 110 vulnerabilities (90 moderate, 19 high, 1 critical) is what I was getting after cloning the origional repo.

**Comment by codesankalp** [comment]
> I tried the same once again. Install is happening and the app loads in browser. I am getting 104 vulnerabilities (85 moderate, 18 high, 1 critical) after npm install but the same 110 vulnerabilities (90 moderate, 19 high, 1 critical) is what I was getting after cloning the origional repo.

Which node and npm verison are you using?

**Comment by umair-fayaz** [comment]
> > I tried the same once again. Install is happening and the app loads in browser. I am getting 104 vulnerabilities (85 moderate, 18 high, 1 critical) after npm install but the same 110 vulnerabilities (90 moderate, 19 high, 1 critical) is what I was getting after cloning the origional repo.
> 
> Which node and npm verison are you using?



> > I tried the same once again. Install is happening and the app loads in browser. I am getting 104 vulnerabilities (85 moderate, 18 high, 1 critical) after npm install but the same 110 vulnerabilities (90 moderate, 19 high, 1 critical) is what I was getting after cloning the origional repo.
> 
> Which node and npm verison are you using?

node v14.17.4, npm 6.14.14

**Comment by codesankalp** [comment]
@umair-fayaz Update the lock file also.

**Comment by umair-fayaz** [comment]
> @umair-fayaz Update the lock file also.

Done!

**Comment by codesankalp** [comment]
@umair-fayaz It worked this time, the updated package-lock.json file was needed.

Screenshot:
image

Can you please make changes to avoid this warning? (Updating your npm may help)

**Review by isabelcosta — COMMENTED** [review]
@umair-fayaz can you please add information about this PR in the description of the PR, as @Aaishpra mentioned?

You can do this like:
edit pull request description

Here's our PR template https://github.com/anitab-org/anitab-forms-web/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

**Comment by umair-fayaz** [comment]
> @umair-fayaz can you please add information about this PR in the description of the PR, as @Aaishpra mentioned?
> 
> You can do this like: edit pull request description
> 
> Here's our PR template https://github.com/anitab-org/anitab-forms-web/blob/develop/.github/PULL_REQUEST_TEMPLATE.md

done!

**Comment by isabelcosta** [comment]
@Aaishpra before we label this "hacktoberfest-accepted" it should have 2 approvals right :) Because it would mean it does not require more changes. If you and @codesankalp or any other contributor approves, feel free to add again :)

**Review by codesankalp — CHANGES_REQUESTED** [review]
@umair-fayaz If we ignore the warnings, then after installing I found three things were updated i.e. `package.json`, `package-lock.json`, and `yarn.lock`.

Can you please update package-lock.json completely or by replacing it with https://gist.github.com/codesankalp/891eae17b6bac00b1baf379403072494 (this is mine which got updated after running npm install)
Also @Aaishpra What do you think about removing `yarn.lock` file?

**Review by codesankalp — COMMENTED** [review]
Thanks, @umair-fayaz, It looks good to me :+1:.
The only thing remaining is to remove or update the `yarn.lock` file. I have asked @Aaishpra about this. After her comment, it will be ready to be merged.

**Comment by umair-fayaz** [comment]
> Thanks, @umair-fayaz, It looks good to me 👍. The only thing remaining is to remove or update the `yarn.lock` file. I have asked @Aaishpra about this. After her comment, it will be ready to be merged.

Sure! thanks

**Comment by Aaishpra** [comment]
> Thanks, @umair-fayaz, It looks good to me 👍. The only thing remaining is to remove or update the `yarn.lock` file. I have asked @Aaishpra about this. After her comment, it will be ready to be merged.

I would prefer updating it instead of removing.

**Comment by Aaishpra** [comment]
> @Aaishpra before we label this "hacktoberfest-accepted" it should have 2 approvals right :) Because it would mean it does not require more changes. If you and @codesankalp or any other contributor approves, feel free to add again :)

Sure Isabel, I added that because there were only small changes required in the PR but as you have mentioned, I think we should go by the rule. Now I will add the label after two approvals 😄

**Comment by umair-fayaz** [comment]
> > Thanks, @umair-fayaz, It looks good to me 👍. The only thing remaining is to remove or update the `yarn.lock` file. I have asked @Aaishpra about this. After her comment, it will be ready to be merged.
> 
> I would prefer updating it instead of removing.

But the file is autogenerated. Updating 'package.json' hasn't caused any changes to 'yarn.lock'. How can I update it?

**Comment by Aaishpra** [comment]
> > > Thanks, @umair-fayaz, It looks good to me 👍. The only thing remaining is to remove or update the `yarn.lock` file. I have asked @Aaishpra about this. After her comment, it will be ready to be merged.
> > 
> > I would prefer updating it instead of removing.
> 
> But the file is autogenerated. Updating 'package.json' hasn't caused any changes to 'yarn.lock'. How can I update it?

I think `yarn upgrade` will work.

**Review by codesankalp — APPROVED** [review]
Thanks @umair-fayaz

**Review by Aaishpra — APPROVED** [review]
Good to go💯

**Pull request merged**
