### PR TITLE
Feature: Activate new registered users by making API request.

### LINKED ISSUE #83: Feature: Activate new registered users by making API request
### Is your feature request related to a problem? Please describe.
For a complete basic authentication system, we need to activate the newly registered users.
When a newly registered user clicks on the activation link sent to the mail it results in a redirection to the Login Page.

### Describe the solution you'd like
Create a new URL in `urls.js` for activating user which will make a GET request to `http://127.0.0.1:8000/api/token_auth/activate/< uidb64 >/< token >`.

The email for activating user contains URL in this format:
`http://localhost:3000/< uidb64 >/< token >`.

So you have to add a Route to this URL also to parse it and make a request to the backend and display the response received from the backend.

### Additional context
This issue needs to be solved after solving this issue https://github.com/anitab-org/open-source-programs-backend/issues/81

### Estimation
1 hour.

### PR DESCRIPTION
**Pull request by codesankalp**
### Description

Added code to activate users from confirmation link sent to the email.
New File Added: `src/components/Activate.js`
Files Changed: 
1. `src/Routes.js`
2. `src/actions/login.js`
3. `src/actions/types.js`
4. `src/reducers/login.js`
5. `src/urls.js`

Fixes #83

### Type of Change:

- Code
- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

register

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by codesankalp** [comment]
For testing it locally, Change your `register.py (osp-backend)` file with this: https://github.com/codesankalp/open-source-programs-backend/blob/activate/token_auth/views/register.py

**Review by jalajcodes — DISMISSED** [review]
Works fine on my machine locally. 🎉
image
image

**Review by Amulya-coder — DISMISSED** [review]
Successfully tested locally 👍

Result:
Expected behaviour: The confirmation email works fine
Actual behaviour: As expected.

image

image

<b>After logging</b>

image

**Comment by Amulya-coder** [comment]
@codesankalp one issue I wanted to point out that it will allow the user to register with the same username as in my SS you can see here I was registered with the test username that you have already used.

**Comment by jalajcodes** [comment]
> @codesankalp one issue I wanted to point out that it will allow the user to register with the same username as in my SS you can see here I was registered with the test username that you have already used.

It's because you are testing locally with your own database.

**Comment by Amulya-coder** [comment]
> > @codesankalp one issue I wanted to point out that it will allow the user to register with the same username as in my SS you can see here I was registered with the test username that you have already used.
> 
> It's because you are testing locally with your own database.

Alright, @jalajcodes I got it thanks for telling :)

**Comment by codesankalp** [comment]
@Amulya-coder and @jalajcodes Thanks for testing and reviewing. :+1: 
@isabelcosta Needs your final review.

**Comment by isabelcosta** [comment]
@codesankalp is it possible to add any test to cover some logic you have added?

**Comment by codesankalp** [comment]
> @codesankalp is it possible to add any test to cover some logic you have added?

I will add tests for this @isabelcosta

**Comment by codesankalp** [comment]
@isabelcosta I am facing problems regarding adding tests for this. I cannot mock Axios response due to `connect` of redux. 
Also, I want to ask which feature or part in this do you want to be tested?
Because API will be tested in the backend and the only thing remaining is component rendering or snapshots which I am trying to do but mocking is giving me errors due to mocking. I also asked for help or better alternatives on zulip and waiting for their answers.

**Comment by codesankalp** [comment]
image
After a lot of researching about it, I was able to figure it out.
Thanks to @mtreacy002 and @isabelcosta for helping me with this.

@jalajcodes, @Amulya-coder, and @isabelcosta Can you review it again?

**Review by Amulya-coder — COMMENTED** [review]
image
@codesankalp I'm trying to test it but it was failing one test in my local can you please check it.

**Comment by codesankalp** [comment]
@Amulya-coder You have to update node-modules with the current `package.json`.
```
rm -rf node_modules/
npm install --force
```
After this test will run successfully.
Let me know if you face any problems.

**Review by Amulya-coder — DISMISSED** [review]
The changes made in this PR were tested locally. Following are the results:

1. Code review: Done
2. All possible responses were tested as:
   Test PR 99 -> Activate the newly registered user from the confirmation link sent to the email and displaying the response received from the backend.
    Screenshot/gif:
image

image
     Tests -> Added tests are working and passed
    Screenshot/gif:
    
image

Expected Result: For the anitab-forms-web add the Authentication system, to activate the newly registered users and add the tests for it.

Actual Result: Successfully confirms the email of a newly registered user and the tests added are passed.

**Comment by Amulya-coder** [comment]
@codesankalp please fix the conflicting files I think it occurs due to the merging of Eslint pr.

**Comment by Amulya-coder** [comment]
@codesankalp QA-checks are failing could you please fix it

**Review by jalajcodes — APPROVED** [review]
LGTM 🙂

- I am able able to register and activate the user.
- Tests are passing successfully.

**Comment by jalajcodes** [comment]
> @codesankalp QA-checks are failing could you please fix it

image


I checked the results and it looks like the lint-action I used doesn't work well with PR's. Check [this issue](https://github.com/wearerequired/lint-action/issues/13) for more info. The workaround suggested in the issue is to not run the linter at all on pull requests, but we want it to run on pull request so we need to look for an alternative.

**Review by Aaishpra — APPROVED** [review]
LGTM👍🏻

**Comment by isabelcosta** [comment]
Amazing @Amulya-coder ! thank you for doing the testing 🙌🏾

**Pull request merged**
