### PR TITLE
docs: Improved Issue Templates and Pull Request Templates

### LINKED ISSUE #89: docs: Improve Issue templates and Pull request templates
### Is your feature request related to a problem? Please describe.
As I saw in the Issue template there are descriptions like `A clear and concise description of what you want to happen.` which is also shown in the preview window unless I remove it manually so it was a time taking process, the description like above should be commented as they are for Author's eye only.

### Describe the solution you'd like
It should be commented like this `<!-- A clear and concise description of what you want to happen. -->`

### Describe alternatives you've considered
N/A

### Additional context
N/A

### PR DESCRIPTION
**Pull request by shruti1421**
### Description

Commented out all necessary statements in the issue template which shouldn't be visible to anyone but only to the author .

Fixes #89 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Aaishpra — COMMENTED** [review]
@shruti1421 great work by commenting out the unnecessary text. Can you change the PR title to `docs: Improve Issue templates and Pull request templates` or something meaningful. I can approve ✅  this then.

**Review by isabelcosta — APPROVED** [review]
Great work @shruti1421 🎉 
Thank you for contributing 🤗

**Review by Amulya-coder — APPROVED** [review]
Well done @shruti1421 approve the changes 🚀
Thanks for your contribution 🎉

**Review by Aaishpra — APPROVED** [review]
🎉 approved

**Review by codesankalp — APPROVED** [review]

**Comment by shruti1421** [comment]
This PR will only be merged if someone having write access approves it. @isabelcosta could you please ask someone who has write access to review and approve this PR.

**Comment by isabelcosta** [comment]
@shruti1421 your first PR here just got merged 👏🏾 🎉

**Pull request merged**
