### PR TITLE
WIP: Add feature to fill, edit and view form responses for users

### LINKED ISSUE #10: As an User, I am able to fill, edit and view the form
## Description
As an User, I am able to fill the form

## Mocks

See https://github.com/anitab-org/open-source-programs-web/wiki/User-Interface-Design for more insights on how it should look like

### Update [Required]
- [ ] Create form feedback page
- [ ] Add check for form deadline
- [ ] Connect API endpoint for creating form feedback
- [ ] Add validations on type of questions
- [ ] Create at least one test for each little feature: Fill form, Edit form and View form

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 days

### PR DESCRIPTION
**Pull request by Aaishpra**
### Description

Currently, this Pull Request is WIP because of some untested features and errors
Will update the description after the PR is complete.

Fixes #10 

### Type of Change:

- Code
- User Interface
- Outreach

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Aaishpra** [comment]
@isabelcosta this PR is not yet completed (basically facing issues while testing these features), and I will not be able to write tests for this feature, (as my university has declared exams and practicals starting from the 5th of this month😢 ) Can you assign the task of writing test (after this features are completed and tested) to someone else in the community.

In the meantime can someone else in the community test and review this PR and suggest some ways I can use to make these features work properly 🙏🏻  (I won't be available much for the time being but will try to make changes to the PR as soon as I get time while giving exams).

Apologies 🙏🏻  from my side, I didn't know I would be stuck in this type of situation and would have to pause my work for this PR.

**Comment by codesankalp** [comment]
@Aaishpra Can you now update the PR?

**Comment by Aaishpra** [comment]
@codesankalp i am currently busy with some commitments will update the work  here after a week

**Comment by Aaishpra** [comment]
Update: I am back and resuming my work on this.

**Comment by isabelcosta** [comment]
Cool @Aaishpra 🤗  thank you for updating us :)

**Comment by codesankalp** [comment]
Is it ready for testing?

**Comment by Aaishpra** [comment]
Facing some compilation error because of  prettier/prettier

**Comment by codesankalp** [comment]
> Facing some compilation error because of prettier/prettier

Ok, Is it happening generally i.e. for develop branch or for this branch?

**Comment by Aaishpra** [comment]
For this branch, basically for preview.js. Don't worry though i will try to compile the code after removing prettier (turn it into warning) and will test if there is a problem with the code or something else

**Comment by Aaishpra** [comment]
> Is it ready for testing?

Can you check if it's working for u or not?

**Comment by codesankalp** [comment]
> > Is it ready for testing?
> 
> Can you check if it's working fir u or not?

Yes, I will check.

**Comment by codesankalp** [comment]
> > Is it ready for testing?
> 
> Can you check if it's working for u or not?

I checked it and tested it for different scenarios. But it's not working for me.
The editing form feature is also not good - the dropdown is in a very small space, if I change the type of question then there is no option for adding options, checkboxes, or choices.

Submitting the form also doesn't seem to work (because the reference to the question is present in the backend but the answer is absent). Also after submitting the form remains open and no success message is shown.

I can't see responses for any form in the submissions tab.

Also, I see there are many commits that are on develop branch that is not present here.

**Comment by codesankalp** [comment]
@Aaishpra Have you addressed issues that I have seen?

**Comment by Aaishpra** [comment]
Sorry, I don't have time to work on this currently. Shall i just close this. @codesankalp

**Comment by codesankalp** [comment]
> Sorry, I don't have time to work on this currently. Shall I just close this. @codesankalp

If you will complete this in the future then there is no point in closing this PR. :+1:

**Comment by Aaishpra** [comment]
Sure then I will get back to it after some time

**Comment by isabelcosta** [comment]
I think we can close this and see if someone else can continue the issue, but if no one picks up and @Aaishpra wants to continue, we can reopen and you can pick up where you left off :)

cc @codesankalp

**Comment by isabelcosta** [comment]
> I think we can close this and see if someone else can continue the issue, but if no one picks up and @Aaishpra wants to continue, we can reopen and you can pick up where you left off :)
> 
> cc @codesankalp

following up on this, I'll close and make the issue available again. Feel free to let us know in the issue if you want to work on this again @Aaishpra

**Comment by Aaishpra** [comment]
No problem Isabel, if the issue is available in future I will get back to it.🙌🏻

**Comment by isabelcosta** [comment]
Nice! Thank you for understanding 🤗

**Pull request closed without merging**
