### PR TITLE
Spelling mistake and comma missing in readme

### LINKED ISSUE #56: Spelling mistake and comma missing in Readme
### Describe the bug
Spelling mistake  ( interact written as intereact ) and a comma missing after the word maintainers, in Readme.

### Screenshots
image

### Additional context
Corrected the errors

### PR DESCRIPTION
**Pull request by Aaishpra**
Fixes #56 
I noticed that there is a spelling mistake in word interact and a comma missing after the word maintainers, hence corrected that.

### Description

Before
image
After
image

### Type of Change:

- Documentation

### CODE REVIEW

**Comment by Aaishpra** [comment]
@bismitaguha
@isabelcosta
@annabauza
@abha224
@saideepesh000
Can anyone please review this.

**Comment by bismitaguha** [comment]
As per contribution guidelines, you should have reported an issue first. The PR is completely fine, but it should have been against a relevant issue.

**Comment by Aaishpra** [comment]
@bismitaguha then should I open a new issue and link this PR there

**Comment by bismitaguha** [comment]
Yes @Aaishpra !

**Comment by Aaishpra** [comment]
Done @bismitaguha

**Review by bismitaguha — APPROVED** [review]

**Comment by bismitaguha** [comment]
@Aaishpra Please give a look to [this issue](https://github.com/anitab-org/open-source-programs-backend/issues/32) too. It's unattended till now!

**Comment by Aaishpra** [comment]
Sure @bismitaguha

**Review by sidvenu — APPROVED** [review]
LGTM!

**Comment by sidvenu** [comment]
@Aaishpra congrats on getting your first PR with @anitab-org merged! :tada:

**Pull request merged**
